### PR TITLE
Disables extremely fast aircraft and adds dollars and euros

### PR DESCRIPTION
**Pull request by sryu1**
Solves 2 from https://github.com/peterclifton/HighAirTrader/issues/4

### CODE REVIEW

**Review by peterclifton — APPROVED** [review]
Thanks!

**Comment by peterclifton** [comment]
Thanks @sryu1 - I like these improvements!

**Comment by peterclifton** [comment]
Pull request merged

**Review by peterclifton — COMMENTED** [review]
Will merge this.  How will we deal with conversions?

**Comment by sryu1** [comment]
I had a think about this, At the current time of writing this, 1 pound is 1.27 USD, and 1.16 Euro. I think it's close enough to each other that we don't really have to deal with conversions...

**Comment by peterclifton** [comment]
Sounds good to me.  So the currency selection will be a cosmetic affair and not touch the underlying numbers which will help keep things simple  :)

**Pull request merged**
